import {$,$$,esc,subjectStats,studentSubjectRows,pct,sortRows,setupSort} from './ui.js';import {exportTableExcel,exportTablePdf,exportTableCsv,formatReportDate} from './export-utils.js';
let data,mode='student',studentId='',subjectId='',section='',from='',to='',sortDir='asc';
export async function render(d){data=d;studentId=d.students[0]?.id||'';draw()}
function filteredLectures(){return data.lectures.filter(l=>(!subjectId||l.subject_id===subjectId)&&(!section||l.section===section)&&(!from||l.lecture_date>=from)&&(!to||l.lecture_date<=to))}
function subset(){const lectures=filteredLectures(),ids=lectures.map(l=>l.id);return{...data,lectures,attendance:data.attendance.filter(a=>ids.includes(a.lecture_id))}}
function draw(){const d=subset();$('#page').innerHTML=`<div class="page-heading"><div><h1>Reports</h1><p>Understand student progress and identify attendance risks.</p></div><div class="segmented"><button data-mode="student" class="${mode==='student'?'active':''}">Student</button><button data-mode="subject" class="${mode==='subject'?'active':''}">Subject</button><button data-mode="short" class="${mode==='short'?'active':''}">Below ${data.settings?.minimum_attendance||75}%</button></div></div><div class="card toolbar"><div class="field grow"><label>Student</label><select class="select" id="student" ${mode==='subject'?'disabled':''}><option value="">All Students</option>${data.students.map(s=>`<option value="${s.id}" ${studentId===s.id?'selected':''}>${esc(s.roll_no)} · ${esc(s.name)}</option>`).join('')}</select></div><div class="field grow"><label>Subject</label><select class="select" id="subject" ${mode==='student'?'':''}><option value="">All Subjects</option>${data.subjects.map(s=>`<option value="${s.id}" ${subjectId===s.id?'selected':''}>${esc(s.subject_name)}</option>`).join('')}</select></div><div class="field"><label>Section</label><select class="select" id="section"><option value="">All</option>${[...new Set(data.students.map(s=>s.section))].map(x=>`<option ${section===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>From</label><input class="input" id="from" type="date" value="${from}"></div><div class="field"><label>To</label><input class="input" id="to" type="date" value="${to}"></div><button class="btn btn-primary" id="apply"><i class="bi bi-funnel-fill"></i> Apply</button></div><div id="reportBody">${mode==='student'?studentReport(d):mode==='subject'?subjectReport(d):shortReport(d)}</div>`;bind()}
function studentReport(d){const st=data.students.find(x=>x.id===studentId);const rows=(subjectId?data.subjects.filter(x=>x.id===subjectId):data.subjects).map(s=>({subject:s,...subjectStats(d,s.id,studentId)})).filter(x=>x.total);const total=rows.reduce((a,x)=>a+x.total,0),present=rows.reduce((a,x)=>a+x.present,0);return `${cards(total,present,total-present,pct(present,total))}<article class="card table-card"><div class="table-head"><div><h2>${esc(st?.name||'Select a student')}</h2><span class="muted">${esc(st?.roll_no||'')} ${st?'· Section '+esc(st.section):''}</span></div><button class="btn btn-soft btn-sm" id="exportReport"><i class="bi bi-download"></i> Export</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Subject</th><th>Present</th><th>Absent</th><th>Total Lectures</th><th>Attendance %</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.subject.subject_name)}</strong></td><td>${x.present}</td><td>${x.absent}</td><td>${x.total}</td><td><strong class="${color(x.percentage)}">${x.percentage}%</strong></td></tr>`).join('')||empty(5)}</tbody></table></div></article>`}
function subjectReport(d){const sub=data.subjects.find(x=>x.id===subjectId);let rows=data.students.filter(s=>!section||s.section===section).map(s=>({student:s,...subjectStats(d,subjectId,s.id)})).filter(x=>x.total);rows=rows.sort((a,b)=>(a.percentage-b.percentage)*(sortDir==='asc'?1:-1));const totalLectures=d.lectures.filter(l=>l.subject_id===subjectId).length,avg=pct(rows.reduce((a,x)=>a+x.present,0),rows.reduce((a,x)=>a+x.total,0));return `${cards(totalLectures,rows.reduce((a,x)=>a+x.present,0),rows.length,avg,['Total Lectures','Present Marks','Total Students','Average Attendance'])}<article class="card table-card"><div class="table-head"><div><h2>${esc(sub?.subject_name||'Select a subject')}</h2><span class="muted">${esc(sub?.subject_code||'')} ${sub?'· '+esc(sub.teacher_name):''}</span></div><button class="btn btn-soft btn-sm" id="exportReport"><i class="bi bi-download"></i> Export</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Roll No</th><th>Student</th><th>Present</th><th>Absent</th><th>Total</th><th class="sortable" data-sort="percentage">Percentage</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.student.roll_no)}</td><td><strong>${esc(x.student.name)}</strong></td><td>${x.present}</td><td>${x.absent}</td><td>${x.total}</td><td><strong class="${color(x.percentage)}">${x.percentage}%</strong></td></tr>`).join('')||empty(6)}</tbody></table></div></article>`}
function shortReport(d){const threshold=Number(data.settings?.minimum_attendance||75);let rows=studentSubjectRows(d).filter(x=>x.percentage<threshold&&(!section||x.student.section===section)&&(!studentId||x.student.id===studentId)&&(!subjectId||x.subject.id===subjectId));return `<article class="card table-card"><div class="table-head"><div><h2>Short Attendance List</h2><span class="muted">Students below ${threshold}% · ${rows.length} records</span></div><div class="actions"><button class="btn btn-outline btn-sm" data-short="csv">CSV</button><button class="btn btn-outline btn-sm" data-short="pdf">PDF</button><button class="btn btn-primary btn-sm" data-short="xlsx">Excel</button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Roll No</th><th>Student Name</th><th>Subject</th><th>Present</th><th>Total Lectures</th><th>Attendance %</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.student.roll_no)}</td><td><strong>${esc(x.student.name)}</strong></td><td>${esc(x.subject.subject_name)}</td><td>${x.present}</td><td>${x.total}</td><td><strong class="text-danger">${x.percentage}%</strong></td></tr>`).join('')||empty(6)}</tbody></table></div></article>`}
function cards(total,present,absent,percentage,labels=['Total Lectures','Present','Absent','Attendance Percentage']){return `<div class="stats-grid" style="grid-template-columns:repeat(4,1fr)">${[['bi-calendar2-week-fill',labels[0],total,'#1677ff','#e6f1ff'],['bi-check-circle-fill',labels[1],present,'#16a65a','#e3f8ed'],['bi-x-circle-fill',labels[2],absent,'#ef4444','#ffe8e9'],['bi-percent',labels[3],`${percentage}%`,'#7857d8','#f0ebff']].map(x=>`<article class="card stat-card" style="--accent:${x[3]};--tint:${x[4]}"><div class="stat-label">${x[1]}</div><div class="stat-value"><span class="stat-icon"><i class="bi ${x[0]}"></i></span>${x[2]}</div></article>`).join('')}</div>`}
function color(n){return n>=90?'text-success':n>=75?'text-blue':'text-danger'}function empty(n){return`<tr><td colspan="${n}"><div class="empty"><i class="bi bi-bar-chart"></i>No report data for these filters.</div></td></tr>`}
function currentRows(){const d=subset();if(mode==='student')return (subjectId?data.subjects.filter(x=>x.id===subjectId):data.subjects).map(s=>{const x=subjectStats(d,s.id,studentId);return{Subject:s.subject_name,Present:x.present,Absent:x.absent,'Total Lectures':x.total,'Attendance %':`${x.percentage}%`}}).filter(x=>x['Total Lectures']);if(mode==='subject')return data.students.map(s=>{const x=subjectStats(d,subjectId,s.id);return{'Roll No':s.roll_no,Student:s.name,Present:x.present,Absent:x.absent,Total:x.total,Percentage:`${x.percentage}%`}}).filter(x=>x.Total);return studentSubjectRows(d).filter(x=>x.percentage<Number(data.settings?.minimum_attendance||75)).map(x=>({'Roll No':x.student.roll_no,'Student Name':x.student.name,Subject:x.subject.subject_name,Present:x.present,'Total Lectures':x.total,'Attendance %':`${x.percentage}%`}))}
function reportExportOptions(){
 const organization={universityName:data.settings?.university_name,className:data.settings?.class_name,semesterName:data.settings?.semester_name};
 if(mode==='student'){
  const selected=data.students.find(s=>s.id===studentId)||{};
    return{organization,title:'STUDENT ATTENDANCE REPORT',fileName:`${selected.name||'Student'}-Attendance-Report`,metadata:[{label:'Student Name',value:selected.name},{label:'Roll Number',value:selected.roll_no},{label:'Section',value:selected.section},{label:'Student Semester',value:selected.semester}],columns:['Subject','Present','Absent','Total Lectures','Attendance %'].map(key=>({key,label:key}))};
 }
 if(mode==='subject'){
  const selected=data.subjects.find(s=>s.id===subjectId)||{};
  return{organization,title:'SUBJECT ATTENDANCE REPORT',fileName:`${selected.subject_name||'Subject'}-Attendance-Report`,metadata:[{label:'Subject',value:selected.subject_name},{label:'Subject Code',value:selected.subject_code},{label:'Teacher',value:selected.teacher_name},{label:'Section',value:selected.section}],columns:[{key:'Roll No',label:'Roll No'},{key:'Student',label:'Student Name'},{key:'Present',label:'Present'},{key:'Absent',label:'Absent'},{key:'Total',label:'Total Lectures'},{key:'Percentage',label:'Attendance %'}]};
 }
 const threshold=Number(data.settings?.minimum_attendance||75);
 return{organization,title:'SHORT ATTENDANCE REPORT',fileName:'Short-Attendance-Report',minimumAttendance:threshold,showSummary:false,metadata:[{label:'Section',value:section},{label:'Subject',value:data.subjects.find(s=>s.id===subjectId)?.subject_name},{label:'From Date',value:formatReportDate(from)},{label:'To Date',value:formatReportDate(to)}].filter(x=>x.value),columns:['Roll No','Student Name','Subject','Present','Total Lectures','Attendance %'].map(key=>({key,label:key}))};
}
function exportMenu(){const rows=currentRows(),options=reportExportOptions();exportTableExcel(options.fileName,rows,options)}
function bind(){$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;if(mode==='subject'&&!subjectId)subjectId=data.subjects[0]?.id||'';if(mode==='short'){studentId='';subjectId=''}draw()});$('#apply').onclick=()=>{studentId=$('#student').value;subjectId=$('#subject').value;section=$('#section').value;from=$('#from').value;to=$('#to').value;draw()};$('#exportReport')?.addEventListener('click',exportMenu);$$('[data-short]').forEach(b=>b.onclick=()=>{const rows=currentRows(),options=reportExportOptions();if(b.dataset.short==='csv')exportTableCsv(options.fileName,rows,options);if(b.dataset.short==='pdf')exportTablePdf(options.title,rows,options);if(b.dataset.short==='xlsx')exportTableExcel(options.fileName,rows,options)});setupSort((k,d)=>{sortDir=d;draw()})}
