import {DB} from './supabase.js';
import {attendanceStats} from './attendance-math.js';
export const $=(s,r=document)=>r.querySelector(s);export const $$=(s,r=document)=>[...r.querySelectorAll(s)];
export const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const fmtDate=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}):'—';
export const pct=(n,d)=>d?+(n*100/d).toFixed(1):0;
export const pageLink=p=>`${p}.html${DB.qs}`;
export const subjectName=(data,id)=>data.subjects.find(x=>x.id===id)?.subject_name||'Unknown subject';
export const studentName=(data,id)=>data.students.find(x=>x.id===id)?.name||'Unknown student';
export function lectureStats(data,lecture){const rows=data.attendance.filter(a=>a.lecture_id===lecture.id);return{rows,...attendanceStats(rows,data.settings?.leave_calculation_policy)}}
export function subjectStats(data,subjectId,studentId=null){const lids=data.lectures.filter(l=>l.subject_id===subjectId).map(l=>l.id);const rows=data.attendance.filter(a=>lids.includes(a.lecture_id)&&(!studentId||a.student_id===studentId));return attendanceStats(rows,data.settings?.leave_calculation_policy)}
export function studentSubjectRows(data){return data.students.flatMap(st=>data.subjects.map(sub=>{const s=subjectStats(data,sub.id,st.id);return{student:st,subject:sub,...s}}).filter(x=>x.total>0))}
export function toast(message,type='success'){let stack=$('.toast-stack');if(!stack){stack=document.createElement('div');stack.className='toast-stack';document.body.append(stack)}const t=document.createElement('div');t.className=`toast ${type}`;t.innerHTML=`<i class="bi ${type==='error'?'bi-exclamation-circle':'bi-check-circle'}"></i><span>${esc(message)}</span>`;stack.append(t);setTimeout(()=>t.remove(),3600)}
export function modal({title='',body='',actions='',small=false}){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal ${small?'sm':''}" role="dialog" aria-modal="true"><div class="modal-head"><h2>${title}</h2><button class="modal-close" aria-label="Close"><i class="bi bi-x-lg"></i></button></div><div class="modal-body">${body}</div>${actions?`<div class="modal-actions">${actions}</div>`:''}</div>`;document.body.append(wrap);const close=()=>wrap.remove();$('.modal-close',wrap).onclick=close;wrap.addEventListener('click',e=>{if(e.target===wrap)close()});return{el:wrap,close,body:$('.modal-body',wrap)}}
export function confirmBox(message,okText='Delete'){return new Promise(resolve=>{const m=modal({title:'Please confirm',small:true,body:`<p class="muted">${esc(message)}</p>`,actions:`<button class="btn btn-outline" data-no>Cancel</button><button class="btn btn-danger" data-yes>${esc(okText)}</button>`});const cancel=()=>{m.close();resolve(false)};$('[data-no]',m.el).onclick=cancel;$('.modal-close',m.el).onclick=cancel;m.el.addEventListener('click',e=>{if(e.target===m.el)cancel()});$('[data-yes]',m.el).onclick=()=>{m.close();resolve(true)}})}
export function sortRows(rows,key,dir='asc'){return [...rows].sort((a,b)=>String(a[key]??'').localeCompare(String(b[key]??''),undefined,{numeric:true})*(dir==='asc'?1:-1))}
const sortDirections=new Map();
export function setupSort(render){$$('.sortable').forEach(th=>th.onclick=()=>{const key=th.dataset.sort,next=(sortDirections.get(key)||'asc')==='asc'?'desc':'asc';sortDirections.set(key,next);render(key,next)} )}
export function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
export const csvCell=v=>`"${String(v??'').replaceAll('"','""')}"`;
export function statusBadge(status){const labels={present:'Present',absent:'Absent',leave:'On Leave',pending:'Pending',approved:'Approved',rejected:'Rejected'},icons={present:'bi-check-circle-fill',absent:'bi-x-circle-fill',leave:'bi-calendar2-minus-fill',pending:'bi-hourglass-split',approved:'bi-check-circle-fill',rejected:'bi-x-circle-fill'};return `<span class="status ${status}"><i class="bi ${icons[status]||icons.absent}"></i>${labels[status]||'Absent'}</span>`}
